### ISSUE TITLE
IO-Compress-Zstd 2.097: depends on IO::Compress::Base 2.097 (not yet released)

### ISSUE THREAD

**Issue by dbevans** [pmqs/IO-Compress-Zstd#2]
The structure of Makefile.PL enforces the requirement that IO::Compress dependencies be
of the same version or greater as IO::Compress::Zstd. 

I note, that in git, the META files indicate the dependency versions as 2.096, which may be
the desired result, but Makefile.PL overrides this and the META files in the CPAN release tarball show 2.097 for the IO::Compress module dependencies.

In any case, build fails in configure since the IO::Compress dependencies have no 2.097 version released as yet.

**Comment by pmqs** [comment]
Thanks David. I usually update the whole lot in one go, so the version numbers are all in sync. In this instance I didn't and forgot about the Makefile.PL

**Comment by pmqs** [comment]
Fixed in 2.098

Just uploaded to CPAN -- https://metacpan.org/release/IO-Compress-Zstd
