### ISSUE TITLE
zstd version v1.5.2

### ISSUE THREAD

**Issue by foobargeez** [pmqs/IO-Compress-Zstd#5]
Hi,
Thanks for the module.  I wanted to try out a couple of enhancements in the latest zstd v1.5.2 - any chance to be able to upgrade the library it as part of this module?

Thanks!

**Comment by pmqs** [comment]
Hey @foobargeez - no plans for updating the version of Zstd at the moment.

If you have a list of features you are interested in, you can add them here.

**Comment by foobargeez** [comment]
Thanks @pmqs.  I am looking to take advantage of the fast and mid compression level performance improvements (introduced in v1.5.0 and v1.5.1 - https://github.com/facebook/zstd/releases).

**Comment by pmqs** [comment]
Hmm, that looks worth doing. I'll add that to my list.

**Comment by foobargeez** [comment]
Thank you.  Would appreciate if you can document the process of upgrading the zstd library while at it and I will be happy to take care of it going forward.

**Comment by foobargeez** [comment]
Just saw a new version of IO::Compress module released -- quite excited that this is being maintained.

Any chance you can upgrade zstd to latest version too?  I am more than happy to volunteer maintaining the module with newer zstd versions once I have steps upgrade the library.

Thanks in advance!

**Comment by pmqs** [comment]
Hey @foobargeez 

I'm not the original author of this code. All I did was branch the original code from https://github.com/spiritloose/Compress-Zstd and add support for streaming, so that I could integrate with my IO::Compress suite of modules.

The current build sucks a specific version of the zstd source and uses only that. An alternative method is to allow the zstd library that is already installed to be used. This makes it much easier to use different versions of the library (as long as the APIU doesn't change). 

I have a prototype of that done that allows easier choice of the version of ZSTD. see the `develop` branch.

usage is this if you want to use the zstd that is installed on your OS

```
perl Makefile.PL
make test
```
To choose the zstd used, set the `ZSTD_LIB` and `ZSTD_INCLUDE` environment variables to the locations of the zstd library & include files respectively.
```
ZSTD_LIB=/usr/local/lib ZSTD_INCLUDE=/usr/local/inbclude perl Makefile.PL
make test
```

The test harness will show a failure in the code that checks for the zstd version -- note I've built with zstd 1.5.4

```
PERL_DL_NONLAZY=1 "/media/paul/Linux-Shared/base/perl/install/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_compile.t .............. ok   
t/01_basic.t ................ # 
# Compress::Stream::Zstd Version 0.203
# ZSTD_VERSION_NUMBER            10504
# ZSTD_VERSION_STRING            1.5.4
# ZSTD_MAX_CLEVEL                22
# ZSTD_MIN_CLEVEL                -131072
# 
t/01_basic.t ................ 1/? 
#   Failed test at t/01_basic.t line 30.
#          got: '10504'
#     expected: '10403'

#   Failed test at t/01_basic.t line 31.
#          got: '1.5.4'
#     expected: '1.4.3'
# Looks like you failed 2 tests of 16.
t/01_basic.t ................ Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/16 subtests 
t/02_streaming.t ............ ok    
t/03_context.t .............. ok   
t/04_dictionary.t ........... ok   
t/05_streaming_windowlog.t .. ok   

Test Summary Report
-------------------
t/01_basic.t              (Wstat: 512 Tests: 16 Failed: 2)
  Failed tests:  8-9
  Non-zero exit status: 2
Files=6, Tests=45,  2 wallclock secs ( 0.04 usr  0.00 sys +  0.31 cusr  0.10 csys =  0.45 CPU)
Result: FAIL
```

**Comment by foobargeez** [comment]
Thanks for getting back and the details.

Compress::Zstd is not being maintained since 2019 :-/  I asked the author for a refresh of zstd 1-2 times but didn't get a reply.

If you're interested in upgrading the zstd library within IO::Compress module suite, Sereal (https://metacpan.org/pod/Sereal), an actively maintained module, started using zstd v1.5.2 with it's latest release (https://metacpan.org/dist/Sereal/changes).  Not sure how much effort it would be to bring the new version into IO::Compress, but it would keep IO::Compress::Zstd up-to-date and importantly, performant.

I am trying to avoid dependencies on locally installed stuff (outside of Perl modules) as much as/whenever I can and thus looking this route.

I would appreciate if you can please take a look at integrating the zstd library from Sereal and port to IO::Compress.  If you can estimate the effort (given that you're familiar with codebase), then we can figure out how to proceed with it.  Being a heavy user of zstd in my Perl backend, I am very much happy to contribute to this effort and interested in using the latest zstd library via IO::Compress or Compress::Zstd or something else for the compression and performance benefits.

Thanks again!

**Comment by pmqs** [comment]
> Thanks for getting back and the details.
> 
> Compress::Zstd is not being maintained since 2019 :-/ I asked the author for a refresh of zstd 1-2 times but didn't get a reply.

I tried as well.

> If you're interested in upgrading the zstd library within IO::Compress module suite, Sereal (https://metacpan.org/pod/Sereal), an actively maintained module, started using zstd v1.5.2 with it's latest release (https://metacpan.org/dist/Sereal/changes). Not sure how much effort it would be to bring the new version into IO::Compress, but it would keep IO::Compress::Zstd up-to-date and importantly, performant.

Sereal doesn't look like it is a natural fit with the IO::Compress modules. It feel more like a variation on protocol buffers. Am I missing something?

> I am trying to avoid dependencies on locally installed stuff (outside of Perl modules) as much as/whenever I can and thus looking this route.

I've just updated the zstd version in https://github.com/pmqs/Compress-Stream-Zstd to use 1.52 & uploaded. That fits with your avoidance of external dependencies.

> I would appreciate if you can please take a look at integrating the zstd library from Sereal and port to IO::Compress. If you can estimate the effort (given that you're familiar with codebase), then we can figure out how to proceed with it. Being a heavy user of zstd in my Perl backend, I am very much happy to contribute to this effort and interested in using the latest zstd library via IO::Compress or Compress::Zstd or something else for the compression and performance benefits.

I remain to be convinced about Sereal  + IO::Compress   :-)

**Comment by foobargeez** [comment]
Thanks for updating Compress::Stream::Zstd with latest zstd 👍 

> Sereal doesn't look like it is a natural fit with the IO::Compress modules

Sorry, I guess I didn't explain it clearly.  I was just quoting the updated zstd library part in Sereal module but not to fit one with another.

I updated the latest Compress::Stream::Zstd in my production and all seems to be looking good so far.

What is the process of updating the module in future with latest zstd version?  I would love to keep it up-to-date.

Thanks again.

**Comment by pmqs** [comment]
> > Sereal doesn't look like it is a natural fit with the IO::Compress modules
> 
> Sorry, I guess I didn't explain it clearly. I was just quoting the updated zstd library part in Sereal module but not to fit one with another.

Aaah, ok.

> I updated the latest Compress::Stream::Zstd in my production and all seems to be looking good so far.

 👍

> What is the process of updating the module in future with latest zstd version? I would love to keep it up-to-date.

To get to, say, 1.5.1, run something like this

```
git clone --recurse-submodules  https://github.com/pmqs/Compress-Stream-Zstd.git
cd Compress-Stream-Zstd
git submodule update --remote
cd ext/zstd
git checkout tags/v1.5.1
cd ../..
git add .
git commit -m "zstd submodule updated to version 1.5.1"
```

**Comment by foobargeez** [comment]
Awesome  -- thanks @pmqs!
